### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/kosciukus/.atom/packages/sync-set...

### ISSUE THREAD

**Issue by kosciukus** [atom-community/sync-settings#247] opened 2016-03-15 19:50 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/kosciukus/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/kosciukus/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/kosciukus/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/kosciukus/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/kosciukus/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/kosciukus/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/kosciukus/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:04.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "8778c517-3bfe-4fb5-9c4e-7e9f0c60b3e3",
    "_lastBackupHash": "a1b9762a0e3ac76dc2abe302e92289f151da3aec",
    "gistId": "859f70f91139a4640845",
    "personalAccessToken": "c8266a6a90ecd543c1b799eee8ec719775538fbf"
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.2.4
hidpi, v0.11.0
highlight-selected, v0.11.2
linter, v1.11.3
open-recent, v5.0.0
pigments, v0.24.5
rest-client, v1.0.0
symbol-gen, v1.0.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-15 19:53
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-15 19:53 UTC
