### ISSUE TITLE
only check for latest version on start - not on new window

### ISSUE THREAD

**Issue by adamreisnz** [atom-community/sync-settings#162] opened 2016-01-07 18:52 UTC
Hi, if I may suggest two small tweaks that will improve the user experience a bit:

1) Only check for latest version of backup when atom starts (as it's advertised in the settings). Currently, it seems to happen for every new window that I open, which seems a bit much. I am unlikely to go to my other computer, change settings, and then come back to my first computer and open a new window and require the new settings.

On the other hand, I do leave my Atom running a long time, so perhaps a better approach would be to just check once a day or so, instead of depending on starting/opening windows. I'll leave that up to you to decide.

2) Don't display the message that the latest backup was already applied. It's distracting me unnecessarily and is blocking part of the editor window for no particular reason. I would be interested to see if backup settings _were_ in fact applied, or if some error occurred, but I don't care to see every day multiple times that my settings were already up to date. Again, I think this is the most common use case, as once someone has set up their editor properly, they will not be making so many changes to their settings anymore.

Thanks for considering :)

**Comment by rahatarmanahmed** [comment] 2016-02-23 20:50
+1

**Comment by rahatarmanahmed** [comment] 2016-02-25 17:00
Looks like the second part was added in #182. Can't wait for this to be released so those damned notifications stop showing up!

**Comment by SavageCore** [comment] 2016-03-03 18:00
@rahatarmanahmed You could for now clone my repo and use it via apm link. That is what I have done until update is pushed.

**Comment by dirk-thomas** [comment] 2016-03-03 18:02
Closing since it is a duplicate of #182. There will likely be a release soon. Until then you can clone the repository.

**Comment by dirk-thomas** [comment] 2016-03-03 18:03
Actually, I will keep this open for the first bullet.

**Comment by adambuczynski** [comment] 2016-03-03 18:46
Thanks :)

**Comment by UziTech** [comment] 2020-02-09 03:19
this was fixed in #182

**Closed by UziTech** 2020-02-09 03:19 UTC
Labels: enhancement
