### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/marcus/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by marcusg** [atom-community/sync-settings#250] opened 2016-03-17 09:07 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/marcus/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/marcus/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/marcus/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/marcus/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/marcus/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/marcus/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/marcus/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -2:58.3.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -2:56.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:55.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-railscast-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "railscast-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "cc7ea692-fd86-4e0b-8637-2f1ed2b95497",
    "_lastBackupHash": "24a89eaa8b4c957ade2134f57232d48e61c6bb2f",
    "analytics": false,
    "gistId": "395738157b1931540d0f",
    "personalAccessToken": "9741d74aad9903ed1712bcf380e3decb28b4d395"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
highlight-selected, v0.11.2
language-rspec, v0.5.0
linter, v1.11.3
linter-rubocop, v0.4.7
minimap, v4.21.0
pigments, v0.24.5
railscast-theme, v0.3.0
ruby-block, v0.3.5
ruby-syntax-replacer, v0.5.1
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-17 09:40
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-17 09:40 UTC

**Comment by marcusg** [comment] 2016-03-17 09:49
Oh sorry. Thanks for the token hint!
Am 17.03.2016 10:40 vorm. schrieb "Jeroen van Warmerdam" <
notifications@github.com>:
