### ISSUE TITLE
`sync-settings` commands not found

### ISSUE THREAD

**Issue by CasperHK** [atom-community/sync-settings#286] opened 2016-07-18 16:37 UTC
After I press <kbd>Ctrl</kbd>+<kbd>P</kbd> and type `sync-settings:backup`. I cannot see the corresponding command found. Previously, the sync-settings' options will be shown while I am typing.

Is this a bug? Or, I have some incorrectly settings?

![2016-07-19 00_32_19-settings g__codespace_resourse atom](https://cloud.githubusercontent.com/assets/6957401/16922510/5c57185c-4d48-11e6-9d3e-db83080ffd00.png)

**Comment by dirk-thomas** [comment] 2016-07-18 23:32
That it weird. Can you please try to uninstall and reinstall the package. If the problem is still the same please provide more information (package version, atom version, platform).

**Comment by CasperHK** [comment] 2016-07-19 15:56
I have uninstalled it and installed it again but it does not work.

When I uninstall it, 2 error messages are shown.
![2016-07-19 23_53_17-settings g__codespace atom](https://cloud.githubusercontent.com/assets/6957401/16956807/6b288d10-4e0c-11e6-8c49-6509186fb696.png)

**Comment by jonyeezs** [comment] 2016-09-08 01:56
I think i've encountered this issue with other packages after uninstalling.

Closing the window and reopening it seem to work for me at one time.

And the other time it happen i had to use the command `window:reload`

or try to uninstall it through apm

**Comment by Conrad2134** [comment] 2016-09-27 13:04
I had the same issue, and here's what worked for me:

1. Uninstall through Atom settings / package view.
2. Close Atom.
3. `apm install sync-settings`
4. Open Atom - all works fine. Gist Id and Access Token were saved, so everything is back to normal.

**Comment by dirk-thomas** [comment] 2016-12-01 05:04
Since this seems to be a package installation / deinstallation issue in Atom / `apm` I will close this ticket since there is presumably nothing we can do in `sync-settings`.

**Closed by dirk-thomas** 2016-12-01 05:04 UTC
Labels: invalid
