### ISSUE TITLE
Is there any way that this package can remove deleted packages?

### ISSUE THREAD

**Issue by JosephTLyons** [atom-community/sync-settings#350] opened 2017-03-18 06:26 UTC
I realize that this seems to only be set up to make sure all Atom systems have the same stuff by adding whats missing, but I dont think its set up to remove extra stuff that may be on the system that isn't on the gist.  For instance, if I delete a package on one machine and sync it via this package to a gist, then bring it down to another machine, that deleted package doesn't get deleted on the second machine.  I assume this isn't something you can support, since after the setting files are downloaded, its purely up to Atom on how to deal with it from there.  Is that correct?  Or is this something that could be supported in the future?  This package is absolutely killer, thats the only thing I wish it could do.  As it is, if I delete 5 or 10 packages, I need to delete them manually on the other systems, which isn't a huge deal since I can pop open the gist history and see which packages were changed and removed, then just do it manually, but it would be convenient if it were automatic.

**Comment by philoserf** [comment] 2017-03-18 07:24
#338 would handle this if it ever gets merged. It is ready...but no action yet.

**Comment by JosephTLyons** [comment] 2017-03-18 07:42
Awesome, I left a comment.

**Comment by dirk-thomas** [comment] 2017-03-20 01:44
Closing as duplicate of #91.

**Closed by dirk-thomas** 2017-03-20 01:44 UTC
Labels: duplicate
