### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by asbjornu** [atom-community/sync-settings#255] opened 2016-03-21 13:19 UTC
I upgraded to v0.7.2 and got this exception during or after upgrade.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/aul/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/aul/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/aul/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/aul/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/aul/.atom/packages/sync-settings/lib/sync-settings.coffee:300:16)
    at Object.SyncSettings.checkForUpdate (/Users/aul/.atom/packages/sync-settings/lib/sync-settings.coffee:61:21)
    at Immediate._onImmediate (/Users/aul/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -2:54.1.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "atom-sharp",
      "autosave"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "c782019c-8ff7-4b7e-ac43-6523f2f21cf6",
    "_lastBackupHash": "858be505161ce57a33ce07dc71103c959fef31de",
    "gistId": "53ff00015073cedbf8a8",
    "personalAccessToken": "cc2f26f603fec63de1f09657d90c0fb071b7edd9"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-yeoman, v0.3.15
autocomplete-clang, v0.8.9
clang-format, v1.25.0
editor-settings, v1.0.4
filesize, v0.4.2
json-schema, v0.1.15
language-bnf, v1.1.0
language-plantuml, v0.2.0
language-powershell, v2.1.0
line-ending-converter, v1.3.2
linter, v1.11.4
markdown-scroll-sync, v2.1.2
plantuml-viewer, v0.7.0
set-syntax, v0.3.0
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-21 16:57
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-21 16:57 UTC

**Comment by asbjornu** [comment] 2016-03-21 18:50
@dirk-thomas Thanks for lett me know about the `personalAccessToken` being shared. I'd appreciate if Atom+sync-settings had masked this in the report, somehow, but I guess that's not an easy thing to do.
