### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages/sync-settings/node_m...

### ISSUE THREAD

**Issue by binarysqueeze** [atom-community/sync-settings#262] opened 2016-04-03 01:43 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.0-beta0
**System**: Mac OS X 10.11.4
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/ian/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:584

Error: ENOENT: no such file or directory, open '/Users/ian/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at Object.module.exports (/Users/ian/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/ian/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/ian/.atom/packages/sync-settings/lib/sync-settings.coffee:300:16)
    at Object.SyncSettings.checkForUpdate (/Users/ian/.atom/packages/sync-settings/lib/sync-settings.coffee:61:21)
    at Immediate._onImmediate (/Users/ian/.atom/packages/sync-settings/lib/sync-settings.coffee:44:19)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -2:42.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "ef3b055d-5853-4c99-a7d0-ffc4c2cdea89",
    "_lastBackupHash": "2b890f749ac46557852dddc63501d105f8b020d4",
    "gistId": "87b925e4cb9377f36d88",
    "personalAccessToken": "5fb96b761b6d97fee77e93d3b78c6f2314784fab"
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
browser-plus, v0.0.54
color-picker, v2.1.1
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.0
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
line-ending-selector, v0.4.1
linter, v1.11.4
linter-eslint, v7.1.3
linter-htmlhint, v1.1.1
linter-jshint, v2.0.4
linter-tslint, v0.9.1
local-history, v3.2.3
monokai, v0.18.0
navigate, v0.1.13
package-manager-commands, v2.0.3
preview-plus, v1.2.6
project-manager, v2.9.3
sync-settings, v0.7.2
synced-sidebar, v0.4.3
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-04-15 12:52
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-04-15 12:52 UTC
