### ISSUE TITLE
Update to use Authorization HTTP header instead

### ISSUE THREAD

**Issue by derPiepmatz** [atom-community/sync-settings#487] opened 2020-02-18 20:07 UTC
**Is your feature request related to a problem? Please describe.**

Recently i get sometimes emails from github that an application is using a deprecated feature which kinda annoys me.

**Describe the solution you'd like**

I don't to get these emails anymore, therefore it should get updated.

**Additional context**

The mail:

> Hi @derPiepmatz,
> 
> On February 18th, 2020 at 19:57 (UTC) your personal access token (Sync-Settings) using NodeJS HTTP Client was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/gists/***
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by UziTech** [comment] 2020-02-18 22:36
duplicate of #463 should be fixed in the latest version

**Closed by UziTech** 2020-02-18 22:36 UTC
