### ISSUE TITLE
Can restore from backup but not back it up

### ISSUE THREAD

**Issue by lukasmalkmus** [atom-community/sync-settings#377] opened 2017-08-21 19:51 UTC
I'm using `sync-settings` for a long time now, but a few days ago creating backups stopped working.

Restoring backups is no problem, but creating one errors with the following message:
```
sync-settings: Error backing up your settings. (Gist ID Not Found)
```

I assigned a new access token, checked the gist ID, reinstalled the package... But it doesn't work. Especially the error is weird, because the gist ID is only known during restore ?!

**Comment by gluons** [comment] 2017-08-23 13:26
Me too. Already set token and Gist id but still face this problem.

**Comment by dirk-thomas** [comment] 2017-08-29 01:53
Do you have a `GITHUB_TOKEN` environment variable set? If yes, this could be a duplicate of #366.

**Comment by gluons** [comment] 2017-08-29 02:23
> **Sync Settings** configuration >> **or** << set it as an environmental variable `GITHUB_TOKEN`

It should be 2 ways to set token, right?  
It seems that **Sync Settings** configuration isn't working now.

Is it posible to change name of environmental variable `GITHUB_TOKEN` (More specific name)?
Sometime I use `GITHUB_TOKEN` for my other work.

**Comment by dirk-thomas** [comment] 2017-08-29 02:28
#374 will give the settings preference again. If that is the problem in your case it should be fixed with the next release.

**Comment by gluons** [comment] 2017-08-29 02:29
Oh! Thank you very much. 🙇‍♀️

**Comment by dirk-thomas** [comment] 2017-08-29 02:47
I will close this for now since it should be fixed by the latest release 0.8.3.

Please feel free to comment with more information if it still doesn't work and the ticket can be reopened.

**Closed by dirk-thomas** 2017-08-29 02:47 UTC

**Comment by IgorGee** [comment] 2017-09-17 14:20
I'm on `0.8.3` and I'm having the same issue.

**Comment by IgorGee** [comment] 2017-09-26 04:21
@dirk-thomas bump

**Comment by dirk-thomas** [comment] 2017-09-26 05:28
@IgorGee Without further information there is not much I can do. I am using the current version of the package and it works just fine.

Please include much more information for your problem (your system, environment, versions, etc.) and try to figure out if anything is different from the "standard" setup / instructions.

**Comment by IgorGee** [comment] 2017-09-27 03:21
I tried getting it to work on 0.7.x versions, making sure the gist was being properly read by the source code, but couldn't understand why it wasn't pushing up any changes.

Strangely enough, I resolved this by getting a new Access Token. Haven't messed with these keys, they've been the same for over a year until now.
