### ISSUE TITLE
Synchronize filetype-specific (scoped) settings

### ISSUE THREAD

**Issue by mdekstrand** [atom-community/sync-settings#121] opened 2015-08-18 18:58 UTC
Right now, sync-settings does not seem to synchronize any of the scoped settings used to configure per-filetype rules such as indent depth. These show up in `config.cson` like so:

```
".gradle.groovy.source":
  editor:
    tabLength: 4
    showIndentGuide: true
```

However, they do not appear on `atom.config.settings`. I do not know how to get or set all of them.

**Comment by rgregg** [comment] 2016-01-22 06:25
+1, this was one of the scenarios I was hoping sync-settings would solve for me!

**Comment by XanderXAJ** [comment] 2016-03-09 19:21
Would it perhaps be possible to sync the settings file by reading and restoring `settings.cson` (instead of going through `atom.config.get` and `atom.config.set`)?

This file is a one stop shop for all settings, and means that we do not have to go digging through undocumented APIs to get the per-grammar settings.

Since Atom monitors `settings.cson` for changes, updates to that file will be read and applied.  There is possibly a chance of a race condition while the file is processed.  This is however how all the other synchronised files operate.

I've actually been toying with the idea locally to see if it could work out.  It seems promising and I'm happy to continue, but I figured I should probably ask here before continuing work on something that isn't wanted. :)

**Comment by dirk-thomas** [comment] 2017-02-03 16:58
I will close this as a duplicate of #289. While this ticket has been there before the other ticket contains more information / discussion on the topic.

**Closed by dirk-thomas** 2017-02-03 16:58 UTC
Labels: enhancement
