### ISSUE TITLE
[DUPLICATED]Uncaught Error: ENOENT: no such file or directory, open '/.atom/packages/syn..

### ISSUE THREAD

**Issue by lippol94** [atom-community/sync-settings#244] opened 2016-03-15 16:22 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/leonardoarcari/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/leonardoarcari/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/leonardoarcari/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/leonardoarcari/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/leonardoarcari/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.restore (/Users/leonardoarcari/.atom/packages/sync-settings/lib/sync-settings.coffee:153:6)
    at atom-workspace.<anonymous> (/Users/leonardoarcari/.atom/packages/sync-settings/lib/sync-settings.coffee:26:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -6:14.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:56.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gl-dark-syntax.theme-one-dark-ui)
     -0:49.8.0 sync-settings:backup (div.panels-item)
     -0:25.6.0 sync-settings:check-backup (div.panels-item)
     -0:16.8.0 sync-settings:view-backup (div.panels-item)
     -0:01.2.0 sync-settings:restore (div.panels-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "gl-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "56fedc09-4727-4099-86f6-4b668fa3da07",
    "_lastBackupHash": "e4ce2423ae8992fe7622fb2893a30681902b6ed8",
    "gistId": "1327d2aa87be0d551d60",
    "personalAccessToken": "d75b5aca97df6a6b58cb3e8aa061844aa40b5fc8"
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autocomplete-clang, v0.8.9
autocomplete-python, v1.7.0
file-icons, v1.6.18
gl-dark-syntax, v2.2.0
java-importer, v1.4.1
language-doxygen, v0.2.1
linter, v1.11.3
linter-flake8, v1.13.0
linter-javac, v1.8.1
open-recent, v5.0.0
python-tools, v0.6.7
sync-settings, v0.7.2
tag, v0.3.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-15 17:11
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-15 17:11 UTC
