### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/david/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by hartbit** [atom-community/sync-settings#239] opened 2016-03-12 21:34 UTC
I updated the package.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/david/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/david/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/david/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/david/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/david/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/david/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/david/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -3:25.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:24.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:24.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:23.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  8x -3:22.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -3:18.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  7x -3:15.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:07.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:06.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -3:04.7.0 core:delete (atom-text-editor.editor.is-focused)
     -3:01.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  6x -3:00.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:59.5.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:38.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:49.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:28.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.theme-base16-tomorrow-dark-theme.theme-one-dark-ui.scrollbars-visible-always)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "f999685f-f884-4b91-9360-99da4d97d5eb",
    "_lastBackupHash": "53174c48718b101681086be6f6e4e556fcfc9509",
    "gistId": "952a2949849bb7125fc9",
    "personalAccessToken": "3755e4d5637daf7e65e8f274b459b91011599de7"
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.3.0
file-icons, v1.6.18
language-swift, v0.4.0
linter, v1.11.3
linter-erb, v1.0.2
linter-ruby, v1.2.2
nuclide-file-watcher, v0.0.32
php-twig, v4.0.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-12 22:57
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-12 22:57 UTC

**Comment by hartbit** [comment] 2016-03-12 23:02
Thanks :(
