### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/varunyellina/.atom/packages/sync-...

### ISSUE THREAD

**Issue by varunyellina** [atom-community/sync-settings#245] opened 2016-03-15 16:59 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/varunyellina/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/varunyellina/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/varunyellina/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/varunyellina/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/varunyellina/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/varunyellina/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/varunyellina/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -7:06.2.0 core:save (atom-text-editor.editor.is-focused)
     -6:52.9.0 core:copy (atom-text-editor.editor.is-focused)
     -6:52.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:51.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:44.3.0 tree-view:remove (span.name.icon.icon-file-text)
     -6:25.5.0 core:copy (atom-text-editor.editor.is-focused)
     -6:25.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:24.4.0 core:save (atom-text-editor.editor.is-focused)
     -6:00.1.0 core:copy (atom-text-editor.editor.is-focused)
     -5:59.5.0 core:select-up (atom-text-editor.editor.is-focused)
     -5:57.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:56.3.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -5:55.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:54.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:54.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:21.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint",
      "markdown-pdf",
      "linter-csslint"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "2205f92f-928d-48b5-8733-02407b7ce33e",
    "_lastBackupHash": "c01b449facaa9ba23382e115378df43112b4eb90",
    "gistId": "8e8e5cc32e598fd123f8",
    "personalAccessToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.26
emmet, v2.4.2
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-js-yaml, v1.2.5
linter-scss-lint, v2.5.1
linter-shellcheck, v1.1.0
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-15 17:12
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-15 17:12 UTC
Labels: duplicate

**Comment by varunyellina** [comment] 2016-03-15 17:18
Thanks for the headsup. Revoked. :+1:
