### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'undefined/atom backup'

### ISSUE THREAD

**Issue by bsussman** [atom-community/sync-settings#404] opened 2018-02-20 13:09 UTC
[Enter steps to reproduce:]

0. put back personal token and gist id that seem to have been blown away
1 Note 'settings out of date' popup
2. Click restore.

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Debian GNU/Linux
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'undefined/atom backup'

```
At fs.js:584

Error: ENOENT: no such file or directory, open 'undefined/atom backup'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at /packages/sync-settings/lib/sync-settings.coffee:255:19
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -0:39.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.has-code-annotations-container)
     -0:28.6.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.has-code-annotations-container.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-bootstrap4 1.4.0 
atom-brackets-glow 0.6.0 
atom-html-templates 0.1.3 
atom-ide-ui 0.8.1 
atom-monokai 0.10.9 
atom-runner 2.7.1 
atom-save-all 0.4.1 
autoclose-html 0.23.0 
autocomplete-date 0.4.0 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
busy-signal 1.4.3 
code-annotations 2.1.3 
colorblind-wombat-dark-syntax 0.6.0 
context-git 0.20.0 
css-snippets 1.1.0 
docblockr 0.13.6 
emmet 2.4.3 
file-icons 2.1.16 
git-log 0.4.1 
git-plus 7.10.0 
git-plus-toolbar 1.0.1 
gitlab 0.1.3-7 
hey-pane 1.1.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
hyperclick-php 0.2.1 
ide-php 0.7.6 
indent-guide-improved 1.4.13 
intentions 1.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.13.0 
language-babel 2.84.0 
language-blade 0.38.0 
language-graphql 0.9.0 
language-hack 0.1.1 
language-haskell 1.17.3 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-jsx 0.1.1 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
laravel 0.7.1 
less-autocompile 1.0.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.1 
linter-htmlhint 1.4.0 
linter-php 1.5.1 
linter-stylelint 4.2.0 
linter-ui-default 1.6.10 
MagicPython 1.0.12 
markdown-preview-plus 2.5.2 
markdown-scroll-sync 2.1.2 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
nuclide 0.283.0 
nuclide-format-js 0.0.44 
permanent-delete 0.1.6 
php-cs-fixer 4.1.1 
php-hyperclick 1.2.1 
pigments 0.40.2 
prettier-atom 0.51.0 
project-manager 3.3.5 
scroll-sync 0.2.4 
set-syntax 0.4.0 
sort-lines 0.18.0 
status-bar-blame 2.0.1 
Sublime-Style-Column-Selection 1.7.4 
swackets 0.35.0 
symbol-gen 1.3.1 
symbols-tree-nav 0.15.5 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
tag 0.5.0 
teletype 0.8.0 
todo-show 2.1.0 
toggle-quotes 1.1.0 
tool-bar 1.1.6 
tree-view-git-branch 0.1.2 
Zen 0.18.0 
```

**Comment by dirk-thomas** [comment] 2018-02-21 06:20
Duplicate of #401.

**Closed by dirk-thomas** 2018-02-21 06:20 UTC
