### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key 

### ISSUE THREAD

**Issue by satsuki0221** [atom-community/sync-settings#175] opened 2016-02-03 16:30 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.2
**Thrown From**: [sync-settings](https://github.com/Hackafe/atom-sync-settings) package, v0.6.0

### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by dirk-thomas** [comment] 2016-07-12 15:32
Can you please clarify what the problem is. The package require an auth token to call the GitHub API so this "intentional". Please see the setup instructions in the readme.

I will close this for now. Please feel free to comment and this can be reopened.

**Closed by dirk-thomas** 2016-07-12 15:32 UTC
