### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/davidhooey/.atom/packages/sync-se...

### ISSUE THREAD

**Issue by davidhooey** [atom-community/sync-settings#248] opened 2016-03-15 21:09 UTC
[Enter steps to reproduce below:]

1. Upgraded to 0.7.2 and stack trace occurred.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/davidhooey/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/davidhooey/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/davidhooey/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/davidhooey/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/davidhooey/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/davidhooey/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/davidhooey/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:20.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-railscast-theme.theme-seti-ui.find-visible)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-write-good",
      "autocomplete-plus"
    ],
    "themes": [
      "seti-ui",
      "railscast-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "e1c87e69-4514-4eb8-adf7-6f488e99867f",
    "_lastBackupHash": "a72ee7c9a866e1e3bfe16ec6afd7ad2208b88a9a",
    "gistId": "c54b03d315fb83f4b0ff",
    "personalAccessToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.2
git-log, v0.4.1
language-haml, v0.23.15
less-autocompile, v1.0.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-htmlhint, v1.1.0
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jshint, v2.0.3
linter-less, v2.4.2
linter-pylint, v1.2.0
linter-ruby, v1.2.2
linter-scss-lint, v2.5.1
minimap, v4.21.0
pretty-json, v0.4.1
railscast-theme, v0.3.0
seti-ui, v0.9.1
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-15 21:50
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Comment by davidhooey** [comment] 2016-03-15 22:15
Thanks! Totally missed that.

**Closed** 2016-03-15 22:38 UTC
Labels: duplicate

**Comment by jerone** [comment] 2016-03-15 22:39
@davidhooey Do you know which version you previously had installed?

**Comment by davidhooey** [comment] 2016-03-15 22:51
I was 0.6.x. I do not know the exact version.

**Comment by jerone** [comment] 2016-03-15 22:52
> It was 0.6.x.

Thanks, I know enough.
