### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/username/.atom/packages/sync-setti...

### ISSUE THREAD

**Issue by thatsprettyfaroutman** [atom-community/sync-settings#240] opened 2016-03-14 07:52 UTC
[Enter steps to reproduce below:]

1. After latest update

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/username/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/username/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/username/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/username/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/username/.atom/packages/sync-settings/lib/sync-settings.coffee:205:9)
    at Object.SyncSettings.checkForUpdate (/Users/username/.atom/packages/sync-settings/lib/sync-settings.coffee:18:3)
    at Immediate._onImmediate (/Users/username/.atom/packages/sync-settings/lib/sync-settings.coffee:35:9)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:27.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-atom-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "git-plus",
      "auto-indent",
      "SFTP-deployment",
      "jsdoc",
      "language-cshtml",
      "merge-conflicts",
      "project-manager",
      "Remote-FTP",
      "atom-color-highlight"
    ],
    "packagesWithKeymapsDisabled": [
      "tidy-tabs"
    ],
    "projectHome": "/Users/username/Documents/projects",
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "d76b2f8b-6899-47bf-bda8-8c8ecec1d0bc",
    "_lastBackupHash": "503ec3a3fb9bf008b5744825476ee6bc10d7bf67",
    "gistId": "b49864c9bc048dbf68a4",
    "personalAccessToken": "0ee942de05ed9252ef3addb07dc59661a4ba0ee8"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.1
atom-alignment, v0.12.1
atom-beautify, v0.28.26
atom-pair, v2.0.10
atom-spotify2, v2.1.2
atom-ternjs, v0.13.2
change-case, v0.6.0
emmet, v2.4.2
file-icons, v1.6.18
language-javascript-jsx, v0.3.7
markdown-preview-plus, v2.2.2
minimap, v4.20.0
php-cs-fixer, v2.5.6
php-twig, v4.0.0
remote-sync, v3.5.0
symbols-tree-view, v0.11.0
sync-settings, v0.7.2
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-14 15:07
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-14 15:07 UTC

**Comment by thatsprettyfaroutman** [comment] 2016-03-14 15:15
Thanks for notifying me :)
