### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/marcello/.atom/packages/sync-sett...

### ISSUE THREAD

**Issue by cello1500** [atom-community/sync-settings#252] opened 2016-03-18 15:59 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/marcello/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/marcello/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/marcello/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/marcello/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/marcello/.atom/packages/sync-settings/lib/sync-settings.coffee:205:9)
    at Object.SyncSettings.checkForUpdate (/Users/marcello/.atom/packages/sync-settings/lib/sync-settings.coffee:18:3)
    at Immediate._onImmediate (/Users/marcello/.atom/packages/sync-settings/lib/sync-settings.coffee:35:9)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
  3x -4:41.2.0 window:move-active-item-to-pane-on-right (atom-text-editor.editor.is-focused)
     -4:34.4.0 window:move-active-item-to-pane-below (atom-text-editor.editor.is-focused)
     -4:33.8.0 window:move-active-item-to-pane-above (atom-text-editor.editor.is-focused)
     -4:06.5.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -3:51.7.0 pane:split-left-and-copy-active-item (atom-text-editor.editor.is-focused)
     -3:39.3.0 pane:split-right-and-move-active-item (atom-text-editor.editor.is-focused)
     -3:29.5.0 application:minimize (atom-text-editor.editor.is-focused)
  2x -3:17.2.0 pane:split-left-and-move-active-item (atom-text-editor.editor.is-focused)
     -2:52.3.0 pane:split-right-and-move-active-item (atom-text-editor.editor.is-focused)
     -2:31.5.0 pane:split-down-and-move-active-item (atom-text-editor.editor.is-focused)
     -2:10.3.0 pane:split-right (atom-text-editor.editor.is-focused)
     -1:39.8.0 pane:close (div.item-views)
     -1:16.9.0 tabs:split-down (div.title)
     -0:36.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "943f8fb1-db86-4adb-8aca-513063aa6b3b",
    "_lastBackupHash": "a84b7933f70d861d0ecd52f9da29f586568e1dd2",
    "analytics": false,
    "gistId": "fd52b8413fa5e6fd0b09",
    "personalAccessToken": "379acbe1e7bcb1805bc8f48f93342e4f77adcf7c"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
go-plus, v4.0.1
go-rename, v0.3.0
language-docker, v1.1.6
language-protobuf, v0.5.0
linter, v1.11.3
minimap, v4.21.0
pigments, v0.24.5
symbols-tree-view, v0.11.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-18 16:34
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-18 16:34 UTC
