### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/USER/.atom/packages/sync-set...

### ISSUE THREAD

**Issue by diogo-gomes** [atom-community/sync-settings#254] opened 2016-03-19 16:39 UTC
**Cannot save settings (backup).**

**Atom Version**: 1.6.0
**System**: Ubuntu 14.04.4
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/USER/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/home/USER/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/home/USER/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/home/USER/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/home/USER/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.backup (/home/USER/.atom/packages/sync-settings/lib/sync-settings.coffee:127:6)
    at atom-workspace.<anonymous> (/home/USER/.atom/packages/sync-settings/lib/sync-settings.coffee:23:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/opt/atom/resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -9:06.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-spacegray-atom-dark-syntax.theme-one-dark-ui)
     -0:01.4.0 sync-settings:backup (div.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-c",
      "language-csharp",
      "language-go",
      "language-less",
      "language-objective-c",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-property-list",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-sql",
      "language-java",
      "language-clojure",
      "terminal-plus",
      "linter-bootlint"
    ],
    "themes": [
      "one-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "SECRET",
    "_lastBackupHash": "SECRET",
    "gistId": "SECRET",
    "personalAccessToken": "SECRET"
  }
}
```

### Installed Packages

```coffee
# User
angular2-snippets, v0.3.0
atom-typescript, v8.4.0
color-picker, v2.1.1
file-icons, v1.6.18
language-docker, v1.1.6
language-javascript, v0.113.0
language-xml, v0.34.4
linter, v1.11.3
linter-csslint, v1.3.2
linter-docker, v0.1.2
linter-htmlhint, v1.1.0
linter-jshint, v2.0.3
linter-jsonlint, v1.2.1
minimap, v4.21.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
pigments, v0.24.5
project-manager, v2.7.6
release-notes, v0.53.0
spacegray-atom-dark-syntax, v1.1.1
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-19 16:41
Duplicate of #194.

**Closed by jerone** 2016-03-19 16:41 UTC
