### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/cyclo/.atom/packages/sync-setting...

### ISSUE THREAD

**Issue by junannko** [atom-community/sync-settings#249] opened 2016-03-17 01:55 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.2
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/cyclo/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/cyclo/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/cyclo/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/cyclo/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/cyclo/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/cyclo/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/cyclo/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -7:01.6.0 find-and-replace:show (input.hidden-input)
     -7:01.4.0 core:paste (input.hidden-input)
     -6:59.8.0 find-and-replace:find-next (input.hidden-input)
     -6:51.6.0 core:copy (input.hidden-input)
     -6:50.5.0 core:move-to-top (input.hidden-input)
     -6:35.5.0 vim-mode:insert-after (input.hidden-input)
     -6:34.2.0 core:move-left (input.hidden-input)
     -6:33.4.0 editor:newline (input.hidden-input)
     -6:32.1.0 core:paste (input.hidden-input)
  2x -6:26.6.0 core:save (input.hidden-input)
     -1:43.6.0 vim-mode:insert-after (input.hidden-input)
     -1:38.8.0 settings-view:open (input.hidden-input)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "keybinding-resolver"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "f25e042e-3fea-465c-b310-ca9b7add92d2",
    "_lastBackupHash": "02c6020e643a73cb59866841e97425725acb3c95",
    "gistId": "7751efe5cdb968d2e7ec",
    "personalAccessToken": "921c9e8b6c5f67eaf60924b6e0b5290d38b90179"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.26
auto-encoding, v0.5.3
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-wordpress-hooks, v0.2.0
color-picker, v2.1.1
emmet, v2.4.2
file-icons, v1.6.18
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
japanese-menu, v1.6.2
linter, v1.11.3
minimap, v4.21.0
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.0
minimap-git-diff, v4.2.0
pigments, v0.24.5
selection-highlight, v0.1.4
show-ideographic-space, v1.0.1
sync-settings, v0.7.2
vim-mode, v0.65.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-17 08:07
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-17 08:07 UTC
