### ISSUE TITLE
Uncaught SyntaxError: Unexpected token g

### ISSUE THREAD

**Issue by chermed** [atom-community/sync-settings#285] opened 2016-07-16 13:14 UTC
Steps

1. Install sync-settings
2. Setup Gist ID and Personnal Token copied from my other machine, (in the other machine backup and restore work well)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.9.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught SyntaxError: Unexpected token g

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22atom%3A%2F%2F.atom%2Fconfig%22%5D%2C%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2Fh1%2Fh216vkys7wj7p3nyfn3q2nrm0000gn%2FT%2F%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22HOME%22%3A%22%2FUsers%2Fmohamedcherkaoui%22%2C%22USER%22%3A%22mohamedcherkaoui%22%2C%22LOGNAME%22%3A%22mohamedcherkaoui%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Ftmp%2Flaunch-0u3bdE%2FListeners%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Ftmp%2Flaunch-swdHw1%2FRender%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0%3A91%5Cn%22%2C%22__CHECKFIX1436934%22%3A%221%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Fmohamedcherkaoui%2F.atom%22%7D%2C%22appVersion%22%3A%221.8.0%22%2C%22atomHome%22%3A%22%2FUsers%2Fmohamedcherkaoui%2F.atom%22%2C%22shellLoadTime%22%3A610%7D:1

SyntaxError: Unexpected token g
    at Object.parse (native)
    at /Users/mohamedcherkaoui/.atom/packages/sync-settings/lib/sync-settings.coffee:204:24
    at [object Object].global.sendError (/Users/mohamedcherkaoui/.atom/packages/sync-settings/node_modules/github4/index.js:729:13)
    at /Users/mohamedcherkaoui/.atom/packages/sync-settings/node_modules/github4/index.js:736:29
    at callCallback (/Users/mohamedcherkaoui/.atom/packages/sync-settings/node_modules/github4/index.js:613:17)
    at ClientRequest.<anonymous> (/Users/mohamedcherkaoui/.atom/packages/sync-settings/node_modules/github4/index.js:684:17)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:996:8)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

### Commands

```
  2x -0:57.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:56.5.0 core:paste (atom-text-editor.editor.is-focused)
  5x -0:47.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:27.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:22.7.0 sync-settings:check-backup (atom-text-editor.editor)
     -0:06.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:01.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 sync-settings:restore (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "*~",
      "*.pyo",
      "*.pyc"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "xxxxxxx",
    "gistDescription": "Atom Se",
    "gistId": "xxxxxxxx",
    "personalAccessToken": "xxxxxxxxx"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.9
autocomplete-paths, v1.0.2
autocomplete-plus, v2.31.1
color-picker, v2.2.2
emmet, v2.4.3
file-icons, v1.7.17
jshint, v1.8.5
linter, v1.11.14
linter-pylint, v1.2.1
minimap, v4.24.7
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
pigments, v0.31.1
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-07-16 15:24
Duplicate of #273. Please comment there with the information requested (the error message from the console).

**Closed by dirk-thomas** 2016-07-16 15:24 UTC
