### ISSUE TITLE
Uncaught SyntaxError: Unexpected token { in JSON at position 3115

### ISSUE THREAD

**Issue by mkmike000** [atom-community/sync-settings#413] opened 2018-02-26 22:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.5

### Stack Trace

Uncaught SyntaxError: Unexpected token { in JSON at position 3115

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:215

SyntaxError: Unexpected token { in JSON at position 3115
    at JSON.parse (<anonymous>)
    at /packages/sync-settings/lib/sync-settings.coffee:236:44
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:03.4.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
sync-settings 0.8.5 
```

**Comment by dirk-thomas** [comment] 2018-02-26 22:27
Closing since the ticket doesn't contain any steps to reproduce. If you provide the mandatory information the ticket can be reopened.

**Closed by dirk-thomas** 2018-02-26 22:27 UTC

**Comment by mkmike000** [comment] 2018-02-26 22:30
I backed up a wrong version of my atom. Then in gist file under revisions I copy and pasted the files locally and uploaded them again in the gist. When I try to restore the uploaded gist files, the error is displayed.

**Comment by dirk-thomas** [comment] 2018-02-26 22:34
Please check the content of your gist (or post a link here) to check if the mentioned position in the file actually does contains invalid JSON.

**Comment by mkmike000** [comment] 2018-02-26 22:48
Thanks, helped!
