### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/*********/.atom/packages/sy...

### ISSUE THREAD

**Issue by Anbacken** [atom-community/sync-settings#242] opened 2016-03-14 15:32 UTC
Happend after update to 0.7.2 and triggers on all actions

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/*******/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/******/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/******/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/****/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/*****/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.backup (/Users/******/.atom/packages/sync-settings/lib/sync-settings.coffee:127:6)
    at atom-workspace.<anonymous> (/Users/******/.atom/packages/sync-settings/lib/sync-settings.coffee:23:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at module.exports._executeCallback (/Users/******/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:71:23)
    at space-pen-button.<anonymous> (/Users/*******/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:30:7)
    at space-pen-button.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-button.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:39.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-robin-hood-syntax.theme-one-dark-ui)
  2x -0:25.3.0 sync-settings:backup (div.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "indent-guide-improved",
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "robin-hood-syntax"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "a06c43aa-400d-4698-87ac-8bf5d8baabad",
    "_lastBackupHash": "5497f8d612383388a5f54512d18c55724aeb9702",
    "extraFiles": [
      "toolbar.cson"
    ],
    "gistId": "94aee610d50ca77813c2",
    "personalAccessToken": "79a9f3a2d9f5807b5f2f87d4934a1f8eff17439d"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-jasmine, v0.8.1
emmet, v2.4.2
file-icons, v1.6.18
flex-tool-bar, v0.8.1
highlight-selected, v0.11.2
linter, v1.11.3
linter-jshint, v2.0.3
pigments, v0.24.5
robin-hood-syntax, v1.0.0
sync-settings, v0.7.2
tasks, v2.6.0
tool-bar, v0.3.0

# Dev
No dev packages
```

**Comment by jerone** [comment] 2016-03-14 16:45
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by jerone** 2016-03-14 16:45 UTC
