### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'C:/WINDOWS\system32\undefined\atom-sync-...

### ISSUE THREAD

**Issue by antronic** [atom-community/sync-settings#402] opened 2018-02-15 17:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package 0.8.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\WINDOWS\system32\undefined\atom-sync-settings'

```
At fs.js:584

Error: ENOENT: no such file or directory, open 'C:\WINDOWS\system32\undefined\atom-sync-settings'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at /packages/sync-settings/lib/sync-settings.coffee:255:19
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -2:18.3.0 core:confirm (input.hidden-input)
     -2:08.2.0 core:close (input.hidden-input)
     -2:05.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -2:02.6.0 core:move-down (input.hidden-input)
     -2:01.3.0 core:move-up (input.hidden-input)
     -2:00.8.0 core:confirm (input.hidden-input)
     -2:00.8.0 sync-settings:backup (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:58.8.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  3x -1:56.7.0 core:move-down (input.hidden-input)
  2x -1:55.7.0 core:move-up (input.hidden-input)
     -1:53.7.0 core:confirm (input.hidden-input)
     -1:53.7.0 sync-settings:backup (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:52.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -1:50.3.0 core:move-down (input.hidden-input)
     -1:49.3.0 core:confirm (input.hidden-input)
     -1:49.3.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.28.26 
atom-material-ui 1.2.6 
atomic-chrome 0.3.0 
color-picker 2.1.1 
css-snippets 0.9.0 
cssbeautify 1.2.0 
emmet 2.4.3 
jade-beautify 0.1.4 
merge-conflicts 1.3.7 
minimap 4.20.0 
minimap-find-and-replace 4.5.0 
open-in-browsers 0.0.11 
pigments 0.24.5 
sync-settings 0.8.3 
```

**Comment by dirk-thomas** [comment] 2018-02-21 06:20
Duplicate of #401.

**Closed by dirk-thomas** 2018-02-21 06:20 UTC
