### ISSUE TITLE
  d65e841a8976f3ce481c026be0637fc266ec1bab

### ISSUE THREAD

**Issue by satsuki0221** [atom-community/sync-settings#296] opened 2016-10-02 12:43 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2
### Stack Trace

Uncaught Error: OAuth2 authentication requires a token or key

**Comment by dirk-thomas** [comment] 2016-12-01 05:05
Duplicate of #284.

**Closed by dirk-thomas** 2016-12-01 05:05 UTC
Labels: duplicate
