### ISSUE TITLE
Error updating backup: latestDate.toISOString is not a function

### ISSUE THREAD

**Issue by aubreyz** [atom-community/sync-settings#512] opened 2020-06-26 20:58 UTC
**Describe the bug**
 Out of the blue it started throwing up this error on every attempt to backup or restore.

![Clipboard-20200626](https://user-images.githubusercontent.com/25100168/85900196-48898a80-b7f7-11ea-9978-87777718e351.png)

The backups seem to be happening OK though. It started immediately after viewing but not changing ion any way the area
under hidden settings (date of last backup). 

I have tried to uninstall and reinstall the package but the error remains. 

**Versions**
 - OS: Windows 10
 - Atom: 1.48.0 x64
 - Sync Settings 4.3.3
 - sync-settings-folder-location 1.0.8 (I am backing up to a local drive)

No idea where to start to troubleshoot this

The last backup time is shown as 2020-06-26T19:07:07.445Z
The only nonstandard setting I have is extra glob: `*.cson, file-templates/*`
Changes to the settings, deleting the backup files and starting again do not help

I even deleted the entire config.cson section after uninstalling the package -- cson that looked like this before deleting
"sync-settings":
    extraFilesGlob: [
      "*.cson"
      "file-templates/*"
    ]
    gistId: ""
    hiddenSettings:
      _lastBackupTime: "2020-06-26T19:07:07.445Z"
    personalAccessToken: ""
    useOtherLocation: true
  "sync-settings-folder-location":
    folderPath: "X:\\GDrive\\Atom Sync"

then reinstalled -- same error

**Comment by aubreyz** [comment] 2020-06-26 21:30
Followup:
After a massive faff which involved essentially reinstalling atom I eliminated the error. 

I managed to re-create the problem by changing the existing 
Extra files glob from
*.cson
to
*.cson,file-templates/*

The files in file-templates/* were copied just fine though - and the "date" error happens on backup before any restore

Reverting the glob to *.cson does not revert the problem however
Nor does deleting the file-templates/* folder

It is highly reproducible and inexplicable

**Comment by UziTech** [comment] 2020-06-26 21:44
The issue seems to be in [`sync-settings-folder-location`](https://github.com/UziTech/sync-settings-folder-location/blob/b07daa5fd3244cdeb92dfba464585b2cf93cd8cd/lib/folder.js#L127) That is the only place I could find that `.toISOString()` was used.

Seems to be an issue getting the modified time of the backup. Could be some sort of permissions issue?

I'll looks into creating a better error message.

**Comment by aubreyz** [comment] 2020-06-26 23:12
I think adding a glob in s particular format is corrupting the settings, and that corruption is not bring reverted even when the glob is. It seems to be causing some sort of remote error. I'll explore more tomorrow.

**Comment by UziTech** [comment] 2020-06-27 02:43
Is there an error in the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>)?

**Comment by aubreyz** [comment] 2020-06-27 14:49
OK I have managed to isolate this error. It is easy to reproduce on my system (Windows 10) on a fresh atom install. You can skip to the end for the bottom line. The long method explains how users will get this error (which is also preventing certain types of backups)

Long method
=============

- New atom install (I simply did a portable install by unpacking the zip install and putyting an empty .atom folder in the next-door position as the atom flight manual explains)
- Packages install sync-settings
- Go to package settings
- Set "Use other location"
- Install sync-settings-folder-location
- Go to settings of above and set folder to an empty folder on file system I created in my case X:\test
- Synch settings > Backup
- Saved copy of config.cson for later comparison #1
- Go to settings of sync-settings
- Under extra files Glob enter `*.cson`
- Run a backup which is successful
- Saved copy of config.cson for later comparison #2
- Change extra files Glob from  `*.cson to *.cson,files/*`
- (as it happens there is nothing that will be picked up by the second glob currently)
- Run a backup - is successful
- Change extra files Glob to *.cson, file-templates/*
- Run a backup - is successful
- Now add some actual files in a folder .atom\file-templates
- Run a backup - is successful *** But produces the error alert each time
- Now remove the files from folder file-templates both in .atom and in the backup (do not delete the folder itself)
- Try running backup again -- and it carries on producing the error!
- Saved copy of config.cson for later comparison #3
- Close atom and revert to cson #2
- Reopen atom - error persists on backup attempt
- Now delete the EMPTY file-templates  folder from backup (which is not referred to in the current settings anyway)
- Reattempt backup - no error now
- Add an empty folder file-templates in the backup
- The error now returns

Short method
==========

Now let us shortcut this whole process
a) Reinstall atom with empty .atom folder
b) Packages install sync-settings -- Go to package settings Set "Use other location"
c) Install sync-settings-folder-location. Go to settings of above and set folder to an empty folder on file system I created in my case X:\test
d) Synch settings > Backup (success)

So far so good

Now simple add an empty folder called file-templates in the backup location

Try repeat the backup, and it throws up errors!!

So the problem is definitely with sync-settings (as the error message indicates) not with sync-settings-folder-location, or anything to do with dates

You can't do any backup which includes subfolders because there cannot be subfolders in the backup folder (even subfolders which were copied across via the backup process itself as in the long method). 
It is obviously useful for a glob to copy settings which exist in a dedicated subfolder (which many packages do such as the file templates package). But although atom will do this it produces these spurious date errors (which depend on the mere existence of a folder)

**Comment by UziTech** [comment] 2020-06-27 14:56
Did you check the console for an error message?

**Comment by UziTech** [comment] 2020-06-27 15:04
I tried the short method and everything worked fine. The only difference was that I created the backup folder on the c drive.

Is your `X` drive an external drive? Try doing it on the `C` drive an see if it still fails.

**Comment by aubreyz** [comment] 2020-06-27 15:26
My X drive is just a partition of my main drive. 

Moved it to the C drive and it does the same. The presence of the error toggles in and out as the folder within the backup is deleted and un-deleted. No subfolder in the backup folder -- no error -- and visa versa 

The only errors on the console (which happen regardless of the error message under discussion) has to do with the files that have not been created yet (as this is a new atom install). Image of error console below.  I also tried the path to the backup folder as both C:/test and C:\test (windows style) and it makes no difference

![Clipboard-20200627](https://user-images.githubusercontent.com/25100168/85925737-60fab300-b892-11ea-884c-93bbbf474282.png)

**Comment by aubreyz** [comment] 2020-06-27 15:41
However ... and things are getting even more peculiar here ... the error depends very reproducibly on exactly what characters there are within the folder name within the backup folder!!!

file-template > error
filetemplate > error
filet > error
f > error
x > no error
f (again) > error
g > error
gg > error
x > No error
xxx > no error
fff > error
iletemplate > error
template > no error
ile > error
i > error
l > no error
e > error
ie > error

**Comment by UziTech** [comment] 2020-06-27 17:33
I can't reproduce it with any of those steps.

Are you still getting the same error "latestDate.toISOString is not a function"?

When you get that error notification do you see an error in the console that says "Error updating backup"? If you find that error can you click the arrow on the left side to expand it and copy the stack trace?

**Comment by aubreyz** [comment] 2020-06-27 19:47
Yes the same error.  However now I noticed two errors in the console that are related (see image). Are you on windows 10 as well? - because I have now tried on a second windows 10 machine that has never had atom installed before -- with the same result. Is there anywhere in the code that could be reading folder names, and in particular the first letter of the name and applying some sort of compute?

Uncaught (in promise) TypeError: latestDate.toISOString is not a function
    at getLastModifiedTime (C:\Users\ablum\Downloads\atom-x64-windows\.atom\packages\sync-settings-folder-location\lib\folder.js:127:20)
    at Object.update (C:\Users\ablum\Downloads\atom-x64-windows\.atom\packages\sync-settings-folder-location\lib\folder.js:221:17)
    at SyncSettings.backup (C:\Users\ablum\Downloads\atom-x64-windows\.atom\packages\sync-settings\lib\sync-settings.js:243:17)
    at async Promise.all (index 0)

![Clipboard-20200627-01](https://user-images.githubusercontent.com/25100168/85930761-ebeda480-b8b6-11ea-82f4-957239304b51.png)

**Comment by aubreyz** [comment] 2020-06-27 20:03
If I scroll all the way to the top of the error stack there is also this, probably unrelated, but not sure whay it is giving these on a fresh install with only these two packages: 

![Clipboard-20200627](https://user-images.githubusercontent.com/25100168/85931086-71725400-b8b9-11ea-8f30-2d6e0c5bd61d.png)

**Comment by aubreyz** [comment] 2020-06-27 20:21
This animated gif shows the wierdness of it

![output](https://user-images.githubusercontent.com/25100168/85931387-19891c80-b8bc-11ea-954a-72083f19201f.gif)

**Comment by UziTech** [comment] 2020-06-27 22:03
According to the stack trace the error is coming from [`sync-settings-folder-location/lib/folder.js:127`](https://github.com/UziTech/sync-settings-folder-location/blob/master/lib/folder.js#L127)

It gets the list of files and folders in the backup folder then checks each one for the latest modified time. That error means it is not able to get the last modified time of any of the files.

**Comment by UziTech** [comment] 2020-06-27 22:06
I am on Windows 10 but I am using Atom v1.49.0-beta0.

I'll try a few more things tonight and probably release a new version to just get more information when that error occurs.

**Comment by UziTech** [comment] 2020-06-28 03:53
I created a branch that will create more logs when the it is trying to get the timestamp.
To install it do the following:

1. Create a folder
2. Open A terminal in the folder and run the following commands
3. Clone the repo: `git clone -b latestDate-error https://github.com/UziTech/sync-settings-folder-location.git .`
4. Install dependencies: `npm i`
5. Install to Atom: `apm link`

After it is installed restart Atom and when the error `'Can not get last modified time'` shows, open the console and see what information is shown.

**Comment by UziTech** [comment] 2020-06-28 05:16
I found the error. Should be fixed by https://github.com/UziTech/sync-settings-folder-location/pull/34

Thank you for taking the time to report this and help debug it. :100:

**Closed** 2020-06-28 05:17 UTC
Labels: needs reproduction

**Comment by UziTech** [comment] 2020-06-28 05:23
look like the first character thing is because it would only fail if the first character of the folder was before any file alphabetically.

This should be fixed in the latest version 1.0.9 of sync-settings-folder-location

**Comment by aubreyz** [comment] 2020-06-28 08:50
Confirm that problem resolved my end after the update. Thanks for great package. 

Can I suggest that docs for one or both packages mention that globs of the form
*.cson,file-templates/* are allowed anyway to backup folders as people may not realise.

**Comment by aubreyz** [comment] 2020-06-28 09:21
Actually there is a bit of a related issue which the bug fix has revealed. I thought I would mention it here in case there is a quick fix since it probably involves the same code. It now backs up the folder fine without error -- but "check for changed backup" now always reports a change -- even when there is none -- with the diff reporting the (unchanged) files within the folder as changed. 

Let me know if best to start a new thread, and if so in which package?

![Clipboard-20200628](https://user-images.githubusercontent.com/25100168/85943600-fea0c180-b928-11ea-94a9-3955891ae45e.png)

**Comment by UziTech** [comment] 2020-06-28 18:04
That issue should be fixed by #515 

I found a few more issues when backing up and restoring backups with folders. Sync-Settings didn't allow syncing folders until recently so there could be more issues. Thanks for taking the time to report issues.

It would be better in the future if you open new issues for each issue so they are easier to track. Opening the issues on this repo are fine unless you know it is an issue with another package. That way more people can find the issue if they have a similar problem.
