### ISSUE TITLE
Uncaught Error: OAuth2 authentication requires a token or key & secret to be set

### ISSUE THREAD

**Issue by P-A-R-U-S** [atom-community/sync-settings#323] opened 2016-12-06 05:00 UTC
Getting following error message after install package.

```
Uncaught Error: OAuth2 authentication requires a token or key & secret to be set
/Users/PARUS/.atom/packages/sync-settings/node_modules/github4/index.js:308
Hide Stack Trace
Error: OAuth2 authentication requires a token or key & secret to be set
    at global.authenticate (/Users/PARUS/.atom/packages/sync-settings/node_modules/github4/index.js:308:23)
    at Object.createClient (/Users/PARUS/.atom/packages/sync-settings/lib/sync-settings.coffee:248:12)
    at Object.restore (/Users/PARUS/.atom/packages/sync-settings/lib/sync-settings.coffee:199:6)
    at atom-workspace.<anonymous> (/Users/PARUS/.atom/packages/sync-settings/lib/sync-settings.coffee:32:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/PARUS/Desktop/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Users/PARUS/Desktop/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Users/PARUS/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Users/PARUS/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Users/PARUS/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/Users/PARUS/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Users/PARUS/Desktop/Atom.
```

**Comment by dirk-thomas** [comment] 2016-12-19 05:16
Did you by any chance trigger the `restore` command before configuring the settings mentioned in the README?

**Comment by joshburgess** [comment] 2016-12-27 20:11
I'm getting the same error all of a sudden after successfully using the plugin for the past year...

**Comment by dirk-thomas** [comment] 2016-12-27 20:28
@joshburgess Please include more information: like the Atom version, the package version, your platform, the stack trace, etc.

**Comment by alexcroox** [comment] 2017-02-09 07:40
I've found despite filling in the package setting fields it rarely seems to save them, despite visually seeing both filled in and having tabbed away/closed settings tab. I found restarted Atom helps see the field the plugin failed to save (in this case Personal Access Token). Re-filling it in then manually unticking and re-ticking the "Sync Settings" tickbox underneath Gist Description helped it finally save the field values. Reproduced on 2 clean installs on different machines.

**Comment by dirk-thomas** [comment] 2017-03-20 01:43
@alexcroox Your description seems to indicate a problem with the setting view. You might want to open the `config.cson` file in parallel to the settings view to see if the entered information are recorded there. If you still experience the problem in the latest Atom version you might want to report the problem [here](https://github.com/atom/settings-view) with a step-by-step reproducible example.

**Comment by rlam3** [comment] 2017-03-26 02:26
is this fixed yet?

**Comment by shaunstanislaus** [comment] 2017-04-11 15:45
not yet fixed, the owner not doing anything about it.

**Comment by dirk-thomas** [comment] 2017-04-11 17:48
@shaunstanislaus The "owner" has requested specific information (hence the label on the ticket) and suggested reporting the problem at a different package. Without more input there is nothing I can do about it.

**Comment by aqueeel** [comment] 2017-05-18 04:32
Worked for me when i relaunched the app after saving ` personalAccessToken`  and `gistId`.

**Comment by sunjay** [comment] 2017-05-24 20:33
@dirk-thomas Thanks for this package! Sorry for some of the responses in this thread. 

I encountered this after the following things happened:
1. I freshly installed atom and subsequently installed sync-settings
2. I restarted atom by clicking "Restart" after a package update

The message popped up and I went into the package settings and found that all my previously entered settings were gone. Do you think it's possible that the settings weren't saved automatically? Maybe by restarting Atom using the package update Restart button instead of closing and reopening normally caused a problem.

Either way, after I entered those settings again, everything seemed to work fine for me. If I find a reproducible way of reaching the issue I'll let you know.

**Comment by dirk-thomas** [comment] 2017-06-14 04:15
I will close the ticket for now since there is not enough information to reproduce / act on in the moment. Please feel free to comment with more information and the ticket can be reopened.

**Closed by dirk-thomas** 2017-06-14 04:15 UTC
Labels: more information needed

**Comment by coolgeng** [comment] 2017-10-19 06:10
Get the same error here. Not sure what kinda information you need to debug.

**Comment by rlam3** [comment] 2017-10-21 02:51
@P-A-R-U-S were you able to get a workaround? It seems it is breaking all the time.

**Comment by P-A-R-U-S** [comment] 2017-10-21 02:55
@rlam3 Unfortunately I did not found workaround. I just minimize using Atom and switch to Gogland.

**Comment by rlam3** [comment] 2017-10-22 02:50
@P-A-R-U-S Thanks! Will definitely check give Gogland a go then... its is taking so long to fix this.

**Comment by philos3** [comment] 2018-05-29 19:41
.atom/packages/sync-settings/node_modules/github/lib/index.js:334

Error: OAuth2 authentication requires a token or key & secret to be set
    at module.exports.authenticate (/.atom/packages/sync-settings/node_modules/github/lib/index.js:334:23)
    at Object.createClient (/.atom/packages/sync-settings/lib/sync-settings.coffee:285:12)
    at Object.backup (/.atom/packages/sync-settings/lib/sync-settings.coffee:167:6)
    at HTMLElement.<anonymous> (/.atom/packages/sync-settings/lib/sync-settings.coffee:28:10)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:384:43)
    at CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:273:17)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/lib/atom/src/atom-environment.js:1333:19)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:326:47)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)

**Comment by chxlvwh** [comment] 2018-11-02 01:43
make sure that the "sync-settings" key is under the "*" in the file "config.cson"

**Comment by kinafu** [comment] 2018-11-25 13:14
> 
> 
> make sure that the "sync-settings" key is under the "*" in the file "config.cson"

If the `personalAccessToken` is not present, the error pops up.
**But** the key of the problem is: It shouldn't be shown as an _uncaught error_.
