### ISSUE TITLE
Following the guide I erased all my settings and  packages

### ISSUE THREAD

**Issue by norcino** [atom-community/sync-settings#411] opened 2018-02-22 18:23 UTC
I followed the guide, configured the package and started a sync Backup.
A lot of notification started to appear and after a bit Atom got stuck.
I restarted Atom and nothing was set up, all packages and customizations lost.
Only me?

I Installed again the package, and the settings are still there.
Still all other packages are gone.

**Comment by dirk-thomas** [comment] 2018-02-24 00:28
Can you reproduce the problem or did it only happened once?

This might be a race condition in Atom itself. The recently announce beta version 1.25.0 mentions addressing problems with concurrent access of the configuration.

**Comment by pugson** [comment] 2018-02-24 18:09
It deleted my gist with settings too! 😡

**Comment by dirk-thomas** [comment] 2018-02-24 18:31
@pugson As for the previous post: please provide reproducible steps. Otherwise there isn't much we can do to help you.

**Comment by pugson** [comment] 2018-02-24 18:33
Steps:
1. Open Atom
2. See package update notification
3. Go to packages view
4. Click update
5. Restart Atom
6. All settings reset in Atom and `sync-settings`

**Comment by norcino** [comment] 2018-02-24 20:21
I just started using Atom, so the first day I explored various settings, customizations, and extensions. The last I have installed was the sync-settings.
I configured the extension and started the synchronization, the first notification appeared, it was green, and it as been followed by a number of blue notification, I wasn't paying attention to the content, when it stopped, I was in the GitHub page and I refreshed it, the gist was empty so I went back to Atom, and it was oddly stuck, so I restarted it, and when it finished restarting I noticed that all my changes were gone, all the extensions where removed.

So in another machine (also this one with Windows 10 Pro, I installed Atom (for the first time) and the first thing I did was to install the sync-settings extension, then I proceeded with others.
When I was happy with the changes I synchronized and I had a series of green notifications.
Then in the original machine used for the first setup, I started a sync restore and it worked.

**Comment by dirk-thomas** [comment] 2018-02-26 18:26
@pugson In the steps you describe none of the `sync-settings` commands is being triggered. So I don't think the problem is related to his package. It might be a problem in Atom itself. The recent beta version (1.25) has some related fixes in that area. Look at the changelog for:

> Perform all configuration file I/O in the main process, to prevent race conditions that occur when multiple windows interact with the configuration file at once.

**Comment by dirk-thomas** [comment] 2018-02-26 18:27
@norcino I am sorry but the information is not specific enough to act on it. Please include the exact steps and the exact output when running into a problem and make sure that you can reproduce it with the latest version.

**Comment by norcino** [comment] 2018-02-27 10:19
@dirk-thomas, the app now works for me, I can sync the settings between two machines, the issue as explained occurred on the first installation and sync.
So for me you can close the issue.

**Comment by dirk-thomas** [comment] 2018-02-27 13:41
Thanks for the response. I will close this for now. Please feel free to comment if you can provide a reproducible example we can look into and the ticket can be reopened.

**Closed by dirk-thomas** 2018-02-27 13:41 UTC
Labels: more information needed
