### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/darrin/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by darrinm** [atom-community/sync-settings#246] opened 2016-03-15 19:47 UTC
1. Updated
2. During the update process: error!

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/darrin/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/darrin/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/darrin/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/darrin/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/darrin/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/darrin/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/darrin/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:43.6.0 pane:split-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
  4x -1:40.1.0 linter:lint (atom-text-editor.editor.hidden-line-numbers)
     -0:59.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-monokai-shade.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "seti-icons",
      "linter-htmlhint"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-shade"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "a7c00e0f-a885-4f29-8f32-a245fa00ca18",
    "_lastBackupHash": "fb1a97c24cbd669ad7cb648f4d541f48261171a9",
    "gistId": "0ec4f693bcc549594cc7",
    "personalAccessToken": "c3afe8ea58f34915c8e1f887d3b7d0afc0e189c7"
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.18
atom-quoteswap, v0.4.6
atom-typescript, v8.3.0
color-picker, v2.1.1
editorconfig, v1.2.4
emmet, v2.4.2
file-icons, v1.6.18
go-plus, v3.5.4
gutter-shadow, v0.6.0
highlight-selected, v0.11.2
language-javascript-semantic, v0.2.1
linter, v1.11.3
linter-csslint, v1.3.2
linter-jshint, v2.0.3
linter-pep8, v1.2.1
minimap, v4.21.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
monokai-shade, v0.3.5
pigments, v0.24.5
rest-client, v1.0.0
sync-settings, v0.7.2
toggle-gutter, v0.2.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-15 19:48
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-15 19:48 UTC
