### ISSUE TITLE
Sync remove package

### ISSUE THREAD

**Issue by crper** [atom-community/sync-settings#305] opened 2016-10-25 10:02 UTC
Can you synchronize the removal of some packages? . I sync in a computer. And then to another computer to synchronize [delete some of the package and change some parameters], and then back in the first too synchronous. . The corresponding plug-in is not deleted and remains in the machine. . This is very bad

**Comment by dirk-thomas** [comment] 2016-10-25 13:31
Duplicate of #91.

**Closed by dirk-thomas** 2016-10-25 13:31 UTC
