### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/pavel/.atom/packages/sync-settings...

### ISSUE THREAD

**Issue by PavelKonon** [atom-community/sync-settings#251] opened 2016-03-18 15:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Ubuntu 15.10
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/pavel/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/home/pavel/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/home/pavel/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/home/pavel/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/home/pavel/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/home/pavel/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/home/pavel/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:08.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "sync-settings": {
    "_analyticsUserId": "a338a5ac-d432-40fb-a6f0-f5efe79754a2",
    "_lastBackupHash": "4172652e67f4d0a5d88917f1f4b35dd21c3495d3",
    "gistId": "0e77f6b2f16c11508d16",
    "personalAccessToken": "fc74577acb75d4b2cc134ba9302bb8ed2b8e2f1e"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
clipboard-plus, v0.5.1
color-picker, v2.1.1
editorconfig, v1.2.4
emmet, v2.4.2
git-log, v0.4.1
language-nginx, v0.6.1
line-diff-details, v1.2.0
local-history, v3.2.3
minimap, v4.21.0
minimap-git-diff, v4.2.0
project-manager, v2.7.6
sync-settings, v0.7.2
terminal-plus, v0.14.5
tidy-tabs, v0.3.0
tree-view-git-status, v0.2.3
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-18 16:33
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-18 16:33 UTC
