### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/200082/.atom/packages/sync-settin...

### ISSUE THREAD

**Issue by kiyodori** [atom-community/sync-settings#260] opened 2016-03-28 12:29 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [sync-settings](https://github.com/atom-community/sync-settings) package, v0.7.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/200082/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/200082/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/routes.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.module.exports (/Users/200082/.atom/packages/sync-settings/node_modules/github/api/v3.0.0/index.js:22:33)
    at new module.exports (/Users/200082/.atom/packages/sync-settings/node_modules/github/index.js:184:26)
    at Object.SyncSettings.createClient (/Users/200082/.atom/packages/sync-settings/lib/sync-settings.coffee:198:18)
    at Object.SyncSettings.checkForUpdate (/Users/200082/.atom/packages/sync-settings/lib/sync-settings.coffee:46:8)
    at Immediate._onImmediate (/Users/200082/.atom/packages/sync-settings/lib/sync-settings.coffee:32:8)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
     -1:37.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:30.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "sync-settings": {
    "_analyticsUserId": "82da9dc5-ca31-43c2-913c-dad1ba734889",
    "_lastBackupHash": "119c9a99817cc88b1bd42c9c285e46e29a19b1da",
    "gistId": "8e77040518b9d7d8be34",
    "personalAccessToken": "6c2485e94d8e6cc6a63dc80bf27363f2af64ecb0"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.5
autocomplete-paths, v1.0.2
builder-go, v1.0.0
color-picker, v2.1.1
environment, v1.2.0
file-icons, v1.6.19
go-config, v1.1.2
go-get, v1.0.2
go-plus, v4.1.0
gofmt, v1.1.3
gometalinter-linter, v1.1.0
gorename, v1.0.0
highlight-selected, v0.11.2
minimap, v4.21.0
minimap-autohide, v0.10.1
navigator-godef, v1.0.2
pigments, v0.26.0
project-manager, v2.8.0
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2
tester-go, v1.0.3

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment] 2016-03-28 15:56
Duplicate of #194.

In the above error report you have shared your `personalAccessToken`. You must revoke it to prevent abuse.

**Closed by dirk-thomas** 2016-03-28 15:56 UTC
