### ISSUE TITLE
Allow to scope settings by platform

### ISSUE THREAD

**Issue by ryinaya** [atom-community/sync-settings#462] opened 2020-01-19 10:52 UTC
Hello.
I develop on different platforms. Some packages need different settings (ex. paths) by platforms.
I heard setting-sync on VSCode has the features that can set parameters for each platform.
So, it could be great if we had a per platform settings set, as same as VSCode.
Or, is there any way to do that on sync-settings in atom already?

(I posted an issue for the first time in my life, and my English is not good. If I have something rude, I'm sorry.)

**Comment by UziTech** [comment] 2020-02-09 01:21
Do you want different settings on different platforms? Could you just set different gists for each platform?

**Comment by hovancik** [comment] 2020-02-09 19:06
It would be nice indeed. From what I understand, my Atom linters only work on macOS because of that.

**Comment by UziTech** [comment] 2020-02-09 19:10
How would sync-settings know which settings should be synced between platforms and which should not?

**Comment by hovancik** [comment] 2020-02-09 19:12
hey @UziTech sorry, I deleted my post meanwhile, the problem was elsewhere for me.  If what @ryinaya says is true, then I guess we could take a look there.

**Comment by UziTech** [comment] 2020-02-10 03:04
closing as duplicate of #159

**Closed by UziTech** 2020-02-10 03:04 UTC
Labels: more information needed
