### ISSUE TITLE
config.cson not fully sync

### ISSUE THREAD

**Issue by borishere** [atom-community/sync-settings#360] opened 2017-05-10 18:50 UTC
Hi, 
Some settings don't sync! For example: 

`".basic.html.text":

  editor:
    showIndentGuide: true
    showInvisibles: false
    softWrap: true
    tabLength: 4
`

**Comment by dirk-thomas** [comment] 2017-05-10 18:51
Duplicate of #289.

**Closed by dirk-thomas** 2017-05-10 18:51 UTC
