### ISSUE TITLE
Settings lost

### ISSUE THREAD

**Issue by tairun** [atom-community/sync-settings#130] opened 2015-09-24 13:01 UTC
I had a problem with some themes. While switching trying out different themes, the less compiler would throw huge amounts of errors (atom won't react properly to anyting, until restart). After restarting, it switched back to the default theme, also the gistID and access token (with the rest of the settings) of the `atom-sync-settings` package were reset.

**Comment by dirk-thomas** [comment] 2016-01-13 17:17
Can you please try to provide some steps to reproduce? Did it ever happen again or only once? Did you try new versions of this package / Atom itself?

**Comment by dirk-thomas** [comment] 2016-03-05 07:24
Without further information this can not be debugged. Assuming this is not a problem anymore I will close this ticket. If you are still experiencing the problem please comment with more information.

**Comment by warent** [comment] 2016-12-02 20:18
I can attest this issue happens to me as well. Although I don't need to switch themes.

For example, when I just rebooted my Arch Linux with Atom running, once the computer started up again and I opened Atom, sync-settings complained about not having a gistID or access token, and my themes were reverted.

**Comment by dirk-thomas** [comment] 2016-12-02 20:21
I assume you had the `gistId` and `personalAccessToken` entered before. And after the restart the settings were gone (permanently)? Are any settings from other packages affected as well?

**Comment by warent** [comment] 2016-12-02 20:23
Correct. If/when this happens again, I will post here what was lost and see if there's any console outputs

**Comment by dirk-thomas** [comment] 2016-12-02 20:24
The console output might contain helpful information. Looking forward for details.

**Comment by warent** [comment] 2016-12-05 17:18
@dirk-thomas Happy Monday! It's happened again.
![screenshot from 2016-12-05 10-17-00](https://cloud.githubusercontent.com/assets/13342266/20894804/17c00e8e-bad4-11e6-8080-043ca2b475c7.png)

Looks like all my packages are here, just the themes have been reset to default and sync settings lost the gist id/token.

**Comment by UziTech** [comment] 2020-02-09 03:12
if this is still an issue in the latest version feel free to reopen

**Closed by UziTech** 2020-02-09 03:12 UTC
Labels: bug, more information needed
